// Generate a "tech stack" showcase page that exercises the icon library —
// grouped rows + a circle-style social-share row + an unknown-slug fallback example.
import {
  composeDesign, frame, rect, hLine, text, hex,
  palettes, icon, iconRow, iconGrid, pasteAxvg, resetIds,
} from "../dist/parser/index.js";

resetIds();
const C = palettes.cool;

const PAGE_PADDING = 24;

function section(y: number, title: string, slugs: string[], opts: { columns?: number; size?: number; circle?: boolean }) {
  const size = opts.size ?? 44;
  const out: any[] = [];
  // Section header
  out.push(text({
    x: PAGE_PADDING, y, w: 375 - PAGE_PADDING * 2, h: 22,
    content: title,
    size: 14, color: C.textMid, typeface: "Inter - Semi Bold", weight: 500,
  }));
  // Icon grid
  if (opts.columns) {
    out.push(...iconGrid(slugs, {
      x: PAGE_PADDING, y: y + 32, size, spacing: 12, rowSpacing: 12,
      columns: opts.columns,
      rounded: opts.circle ? "circle" : "rounded",
    }));
  } else {
    out.push(...iconRow(slugs, {
      x: PAGE_PADDING, y: y + 32, size, spacing: 10,
      rounded: opts.circle ? "circle" : "rounded",
    }));
  }
  return out;
}

const page = frame({
  name: "技术栈展示",
  w: 375, h: 1200, // taller — lots of sections
  bg: C.bg,
  children: [
    // Header
    text({ x: 0, y: 60, w: 375, h: 32, content: "我的技术栈",
           size: 24, color: C.textDark, typeface: "Inter - Bold", weight: 700, align: "center" }),
    text({ x: 0, y: 96, w: 375, h: 18, content: "Built with my favorite tools",
           size: 13, color: C.textLight, align: "center" }),

    hLine({ x: PAGE_PADDING, y: 140, w: 375 - PAGE_PADDING * 2, color: C.border }),

    // Languages row
    ...section(170, "LANGUAGES", ["ts", "js", "py", "go", "rust", "kotlin"], { columns: 6, size: 44 }),

    // Frontend frameworks
    ...section(286, "FRONTEND", ["react", "vue", "svelte", "nextjs", "tailwind", "vite"], { columns: 6, size: 44 }),

    // Backend
    ...section(402, "BACKEND", ["nodejs", "fastapi", "spring", "django", "rails", "nestjs"], { columns: 6, size: 44 }),

    // Cloud & DevOps
    ...section(518, "CLOUD & DEVOPS", ["aws", "vercel", "cloudflare", "docker", "kubernetes", "github"], { columns: 6, size: 44 }),

    // Design tools
    ...section(634, "DESIGN", ["figma", "ps", "ai", "blender"], { columns: 6, size: 44 }),

    hLine({ x: PAGE_PADDING, y: 740, w: 375 - PAGE_PADDING * 2, color: C.border }),

    // Find me on — circle social chips
    text({ x: 0, y: 770, w: 375, h: 22, content: "FIND ME ONLINE",
           size: 14, color: C.textMid, typeface: "Inter - Semi Bold", weight: 500, align: "center" }),
    ...iconRow(["github", "twitter", "linkedin", "discord", "stackoverflow", "devto"], {
      x: 51, y: 808, size: 44, spacing: 10, rounded: "circle",
    }),

    hLine({ x: PAGE_PADDING, y: 884, w: 375 - PAGE_PADDING * 2, color: C.border }),

    // Big primary stack — larger icons
    text({ x: 0, y: 914, w: 375, h: 22, content: "PRIMARY STACK",
           size: 14, color: C.textMid, typeface: "Inter - Semi Bold", weight: 500, align: "center" }),
    ...iconRow(["ts", "react", "tailwind", "postgres"], {
      x: 51, y: 950, size: 64, spacing: 16, rounded: "rounded",
    }),
    text({ x: 0, y: 1030, w: 375, h: 18, content: "TypeScript · React · Tailwind · Postgres",
           size: 12, color: C.textLight, align: "center" }),

    // Unknown slug example (renders as neutral placeholder)
    text({ x: 0, y: 1080, w: 375, h: 18, content: "Unknown slug fallback:",
           size: 11, color: C.textLight, align: "center" }),
    ...iconRow(["xyzdoesnotexist", "alsoun­known"], {
      x: 130, y: 1108, size: 44, spacing: 10,
    }),

    // Footer
    text({ x: 0, y: 1170, w: 375, h: 16, content: "Generated by axure-mcp · /SKILL_AXVG.md",
           size: 10, color: C.textLight, align: "center" }),
  ],
});

const design = composeDesign(page);
console.log(`Generated tech-stack page: JSON ${JSON.stringify(design).length} chars`);
const result = pasteAxvg(design, { autoPaste: true });
console.log(JSON.stringify(result, null, 2));
